{
 "title": "Tempiture",
 "description": "Tempiture Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "chamber1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    { "target": "data.chamber1.temperature" }
   ]
  },
  {
   "title": "Chamber Average",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    { "target": "data.chamber_avg.temperature" }
   ]
  },
  {
   "title": "Temperature Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "data.gas.mode" }
   ]
  },
  {
   "title": "meat1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    { "target": "data.meat1.temperature" }
   ]
  },
  {
   "title": "Manual Mode Controls",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "content": "<SCRIPT>\nvar myGloc = window.location.protocol + \"//\" + window.location.hostname + \":5000\";\nvar myGSet = myGloc + \"/setgas/\";\nvar myGMove = myGloc + \"/movegas/\";\n</SCRIPT>\n<CENTER>\n<TABLE>\n<TR><TD colspan=6><CENTER><H2>Set Gas Level</H2></CENTER></TD></TR>\n<TR>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGSet + '0');\">0%</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGSet + '25');\">25%</button></TD>\n<TD colspan=2><CENTER><button style=\"color:black\" onclick=\"$.ajax(myGSet + '50');\">50%</button></CENTER></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGSet + '75');\">75%</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGSet + '100');\">100%</button></TD>\n</TR>\n<TR><TD colspan=6><CENTER><H2>Move Gas Level</H2></CENTER></TD></TR>\n<TR>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGMove + '-25');\">-25%</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGMove + '-10');\">-10%</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGMove + '-1');\">-1%</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGMove + '1');\">+1%</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGMove + '10');\">+10%</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myGMove + '25');\">+25%</button></TD>\n</TABLE>\n</CENTER>\n\n\"\""
  },
  {
   "title": "Auto Mode Temp Controls",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "content": "<SCRIPT>\nvar myTloc = window.location.protocol + \"//\" + window.location.hostname + \":5000\";\nvar myTSet = myTloc + \"/settarget/\";\nvar myTMove = myTloc + \"/movetarget/\";\nvar myTAuto = myTloc + \"/setauto\";\n\n</SCRIPT>\n<CENTER>\n<TABLE>\n<TR><TD colspan=2><CENTER><H2>Target Temp</H2></CENTER></TD><TD colspan=\"4\"><CENTER><button style=\"font-size: larger; color:black\" onclick=\"$.ajax(myTAuto);\">Toggle Auto</button></CENTER></TD></TR>\n<TR>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTSet + '140');\">140</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTSet + '160');\">160</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTSet + '180');\">180</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTSet + '200');\">200</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTSet + '220');\">220</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTSet + '240');\">240</button></TD>\n</TR>\n<TR><TD colspan=6><CENTER><H2>Move Target Temp</H2></CENTER></TD></TR>\n<TR>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTMove + '-10');\">-10</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTMove + '-5');\">-5</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTMove + '-1');\">-1</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTMove + '1');\">+1</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTMove + '5');\">+5</button></TD>\n<TD><button style=\"color:black\" onclick=\"$.ajax(myTMove + '10');\">+10</button></TD>\n</TABLE>\n</CENTER>\n\n"
  },
  {
   "title": "chamber2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    { "target": "data.chamber2.temperature" }
   ]
  },
  {
   "title": "Gas Level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "target": "data.gas.level" }
   ]
  },
  {
   "title": "Chamber Target",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    { "target": "data.chamber_avg.target" }
   ]
  },
  {
   "title": "meat2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    { "target": "data.meat2.temperature" }
   ]
  },
  {
   "title": "Target Graph",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "target": "alias(exponentialMovingAverage(data.chamber_avg.temperature, 10), 'chamber_avg')"
    },
    {
     "target": "alias(exponentialMovingAverage(data.chamber_avg.target, 1), 'target')"
    }
   ]
  },
  {
   "title": "Probe Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(exponentialMovingAverage(data.chamber1.temperature, 10), 'chamber1')"
    },
    {
     "target": "alias(exponentialMovingAverage(data.chamber2.temperature, 10), 'chamber2')"
    },
    {
     "target": "alias(exponentialMovingAverage(data.meat1.temperature, 10), 'meat1')"
    },
    {
     "target": "alias(exponentialMovingAverage(data.meat2.temperature, 10), 'meat2')"
    }
   ]
  },
  {
   "title": "Smoke Label",
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "content": "<SCRIPT>\nvar myloc = window.location.protocol + \"//\" + window.location.hostname + \":5000\";\nvar myGet = myloc + \"/getlabel\";\nvar mySet = myloc + \"/setlabel/\";\n</SCRIPT>\n<TABLE> \n<TR>\n  <TD colspan=1>Smoke Labeling: All Data from this smoke will be tagged with the name you give it here:</TD>\n  <TD><INPUT id=\"smokelabel\" type=\"textbox\" value=\"\"></INPUT></TD>\n</TR>\n<TR>\n  <TD colspan=1>\n    <IFRAME width=\"350\" style=\"color:white\" id=\"myiframe\" src=\"\"></IFRAME></CENTER>\n  </TD>\n  <TD>\n    <button style=\"color:black\" onclick=\"$.ajax(mySet + $('#smokelabel').val()); $('#smokelabel').val('') ;\">Set Label</button>\n  </TD>\n</TR>\n</TABLE>\n<SCRIPT>\ndocument.getElementById(\"myiframe\").src = myGet;\nsetInterval(function (){\nvar iframe = document.getElementById(\"myiframe\");\niframe.src = iframe.src;\n}, 5000);\n</SCRIPT>\n\n\n\n\n\n"
  },
  {
   "title": "Smoke Notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 15 },
   "content": "<SCRIPT>\nvar myNloc = window.location.protocol + \"//\" + window.location.hostname + \":5000\";\nvar myNGet = myNloc + \"/getnotes\";\nvar myNSave = myNloc + \"/savenote/\";\n</SCRIPT>\n<TABLE> \n<TR>\n  <TD colspan=2>\n    You can you use this to save simple notes about your smoke. The Smoke Label and Time of Note are automatically included as part of the saved note.\n  </TD>\n</TR>\n<TR>\n  <TD>\n    <INPUT id=\"smokenote\" type=\"textbox\" size=\"180\" value=\"\"></INPUT>\n  </TD>\n  <TD><button style=\"color:black\" onclick=\"$.ajax(myNSave + $('#smokenote').val()); $('#smokenote').val('') ;\">SaveNote</button></TD>\n</TR>\n<TR>\n  <TD colspan=2>\n    <IFRAME width=\"1150\" style=\"color:white\" id=\"noteiframe\" src=\"\"></IFRAME>\n  </TD>\n</TR>\n</TABLE>\n<SCRIPT>\ndocument.getElementById(\"noteiframe\").src = myNGet;\nsetInterval(function (){\nvar iframe = document.getElementById(\"noteiframe\");\niframe.src = iframe.src;\n}, 10000);\n</SCRIPT>\n\n"
  }
 ]
}